### ISSUE TITLE
怎么才能弄明白这个项目如何用机器学习计算特征值的?

### ISSUE THREAD

**Issue by qyf404** [wfh45678/radar#21]
如题, 我想学习一下计算特征值的方法, 想问一下要从哪个模块看起? 
wiki中我看到是有对机器学习支持的, 但是我在演示环境和代码中没有看到计算的入口.

**Comment by wfh45678** [comment]
你好，特征值的计算，请查看  AggregateCommand 接口 及其实现类，
机器学习还在进行中，  另外 演示环境暂时不提供计算功能，后续升级配置后会提供engine端计算功能

**Comment by wfh45678** [comment]
另外，机器学习不是用来计算特征值的， 是把计算好的特征值，喂到机器学习模型里面进行计算

**Comment by qyf404** [comment]
谢谢解答. 特征值的确定是这么一个流程.
1. 定义 一个特征值.
2. 用已有的数据跑一下这个特征值的拦截情况.
3. 看看这个特征值的拦截情况, 然后优化.优化基本是两个方向, 一个是重新定义特征值, 另一个是修改阈值.

**Comment by wfh45678** [comment]
相当于这是业务专家干的活， 而机器学习相当于干点业务专家的活，更快的找到合适的值和特征

**Comment by qyf404** [comment]
多谢解答.
