### ISSUE TITLE
报表查询->规则命中 查询具体结果与预期不符合

### ISSUE THREAD

**Issue by cheng0571** [wfh45678/radar#44]
由于规则命中页面 查询的是所有数据中命中规则的记录,但是点击查看明细,查询具体结果时候默认携带查询日期,无法查询到命中规则的记录,容易产生混淆.
建议规则命中页面也带一个日期?无需直接查询所有数据,跳转至查询页面时候携带时间参数
亦或者其他更好的符合业务的方式

**Comment by wfh45678** [comment]
done
