### ISSUE TITLE
druid这个是配置什么的？

### ISSUE THREAD

**Issue by ylmcr7** [wfh45678/radar#78]
![image](https://user-images.githubusercontent.com/63889450/112428764-9e836280-8d76-11eb-9430-c9c5d6a00a41.png)
/opt/radar/radar-engine/src/main/resources/application-dev.yml  

    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456

**Comment by wfh45678** [comment]
druid admin 的用户名和密码

**Comment by ylmcr7** [comment]
druid是做什么的？
