### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by JamieSlome** [wfh45678/radar#89]
Hey there!

I belong to an open source security research community, and a member (@ready-research) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by wfh45678** [comment]
done.

**Comment by JamieSlome** [comment]
@wfh45678 - thanks 😄 

Just for reference, you can find the report directly here too:

https://huntr.dev/bounties/8e1b65d9-7820-45e9-af53-54dd828fe4c4/

It is private and only accessible to maintainers with repository write permissions.

**Comment by ready-research** [comment]
@wfh45678 Any update on this issue?

**Comment by wfh45678** [comment]
Hi, the upload dir is a tmp dir, only can be load by code, but I will check the file's postfix after unzip.
